version: '3'
services:
  pic-viewer:
    image: ntdtfr/pic-viewer
    ports:
    - 8090:5000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]