version: '3'
services:
  pic-viewer:
    image: ntdtfr/pic-viewer
    ports:
      - 8090:5000
    networks:
      - pvnet
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
networks:
  pvnet: