version: '3'
services:
  nginx:
    image: nginx:1.13
    restart: always
    ports:
    - 8080:80
    - 8443:443
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    depends_on:
    - web
    networks:
    - webnet

  web:
    image: ntdtfr/pic-viewer
    restart: always
    volumes:
    - /Users/ntran/Datas/pictures:/pic-viewer/static
    networks:
    - webnet
      
networks:
  webnet:
