version: '3'
services:
  nginx:
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    depends_on:
    - pic-viewer
    networks:
    - webnet

  pic-viewer:
    image: ntdtfr/pic-viewer
    restart: always
    ports:
    - 5000:5000
    # volumes:
    # - /Users/ntran/Datas/pictures:/pic-viewer/static
    networks:
    - webnet
      
networks:
  webnet:
